---
- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
    - php
    - apache2
    - libapache2-mod-php
    - php-gd
    - libssh2-php
    - php-mcrypt
    - php-mysql
